### ISSUE TITLE
Bash fails on MacOSX

### ISSUE THREAD

**Issue by taldcroft** [sot/Ska.Shell#11]
Have not looked at this, but it stops `run_testr` from getting out of the starting blocks.
```
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /Users/aldcroft/miniconda3/envs/ska3-test/bin/python
cachedir: .cache
rootdir: /Users/aldcroft/git/Ska.Shell, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 20 items                                                                                                                                              

Ska/Shell/tests/test_shell.py::TestSpawn::test_ok PASSED
Ska/Shell/tests/test_shell.py::TestSpawn::test_os_error PASSED
Ska/Shell/tests/test_shell.py::TestSpawn::test_timeout_error PASSED
Ska/Shell/tests/test_shell.py::TestSpawn::test_grab_stderr PASSED
Ska/Shell/tests/test_shell.py::TestSpawn::test_multi_stdout PASSED
Ska/Shell/tests/test_shell.py::TestSpawn::test_shell_error PASSED
Ska/Shell/tests/test_shell.py::TestBash::test_bash FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_bash_shell FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_env FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_promptenv FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_importenv FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_logfile FAILED
Ska/Shell/tests/test_shell.py::TestBash::test_ciao FAILED
Ska/Shell/tests/test_shell.py::TestTcsh::test_tcsh PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_tcsh_shell PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_env PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_importenv PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_logfile PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_ascds PASSED
Ska/Shell/tests/test_shell.py::TestTcsh::test_ciao PASSED
```
I'm suspicious that the `tcsh` ascds and ciao tests PASSED since I have no CIAO nor ASCDS on this machine.

**Comment by jeanconn** [comment]
Not sure what we consider the required minimum environment on mac.  I'll look at this from a skare3 perspective, but I believe I have a bash installed on both of my test machines (if the error is because it is missing).

**Comment by jeanconn** [comment]
Also can't tell what version of Ska.Shell you are testing if you are just working out of your git repo

**Comment by taldcroft** [comment]
That is Ska.Shell master (testing out of git repo) on my Mac laptop.  Bash is the default shell on mac and we can assume it is always there.  (In other words, the error is not for lack of bash).

Sorry, didn't paste in the pages and pages of errors, but it looked perhaps like pexpect was not getting what it expected.

**Comment by jeanconn** [comment]
At ddd913572 this looks fine for me on both laptops.  The only fail I have is on bash ciao, which I expect.  The ascds and ciao tcsh tests look weak.

**Comment by taldcroft** [comment]
OK, good info.  So this is the problem in my .bash_profile:
```
export PROMPT_COMMAND='echo -ne "\033]0;`/Users/aldcroft/bin/chop_dir $PWD`\007"'
```
Maybe there is a code fix, but in the meantime I can live without the nicer dir info in my shell tabs.  (chop_dir makes a long dir name fit into something reasonable).

**Comment by jeanconn** [comment]
Good catch.  Maybe we should open another issue to indicate that #10 was not the panacea I had hoped.
