### ISSUE TITLE
Documentation building does not work in newer python (I guess)

### ISSUE THREAD

**Issue by javierggt** [sot/Ska.Shell#24]
There are some private functions explicitly documented in index.rst. This breaks the docs generation because private names are not imported by `from .shell import *` in \_\_init__.py. I think this is an issue with newer python, but I have not tested it with older python.

One has to do one of these:
- explicitly import them in \_\_init__.py.
- fully qualify them in index.rst
- remove them from index.rst

 I would say that private functions do not belong in the documentation. If we want them there, then I'd say they should be fully qualified.

**Comment by taldcroft** [comment]
I'm happy removing them from index.rst.  This is all very ancient stuff, though even then I should have known better. I.e. I agree with the last two sentences above.

**Comment by javierggt** [comment]
The private members were removed and changes are merged into master.
